config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from loyalty_app.views import process_login
from user_profile.views import process_admin_login

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', process_admin_login, name='login'),
    path('', process_login, name='loyalty_login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('/logout/', auth_views.LogoutView.as_view(next_page='loyalty_login'), name='loyalty_logout'),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    path('users/', include('user_profile.urls'), name='users'),
    path('treatments/', include('treatments.urls'), name='treatments'),
    path('patients/', include('patients.urls'), name='patients'),
    path('appointments/', include('appointments.urls'), name='appointments'),
    path('', include('loyalty_app.urls'), name='loyalty'),
    path('transactions/', include('transactions.urls'), name='transactions'),
    path('redeem_points/', include('redeem_points.urls'), name='redeem_points'),
    path('offers/', include('offers.urls'), name='offers'),
    path('reports/', include('reports.urls'), name='reports'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'

urlpatterns = [
    path('report', views.report, name='report'),
    path('appointment-report', views.appointment_report, name='appointment_report'),
    path('patient-list-report', views.patient_list_report, name='patient_list_report'),
    path('treatment-list-report', views.treatment_list_report, name='treatment_list_report'),
    path('canceled-appointment-report', views.canceled_appointment_report, name='canceled_appointment_report'),
    path('total-sales', views.total_sales, name='total_sales'),

]

reports/models.py
from django.db import models

# Create your models here.

reports/forms.py
from django import forms


class AppointmentDateRangeForm(forms.Form):
    date_from = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    date_to = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))


class PatientDateRangeForm(forms.Form):
    date_from = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    date_to = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))


class TreatmentDateRangeForm(forms.Form):
    date_from = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    date_to = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))


class CancelDateRangeForm(forms.Form):
    date_from = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    date_to = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))


class SalesDateRangeForm(forms.Form):
    date_from = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    date_to = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

reports/views.py
from django.contrib.auth.decorators import login_required, permission_required

from reports.forms import AppointmentDateRangeForm, PatientDateRangeForm, TreatmentDateRangeForm, CancelDateRangeForm, \
    SalesDateRangeForm
from django.shortcuts import render

from reports.utils import most_availed_treatment, get_patients, get_treatments, get_canceled_appointment, \
    total_sales_report
from user_profile.decorators import admin_required

from django.contrib.auth.models import User

# Create your views here.


@login_required
@admin_required
@permission_required('user_profile.view_user', raise_exception=True)
def report(request):
    return render(request, 'reports.html')


def appointment_report(request):
    form = AppointmentDateRangeForm(request.POST or None)
    if form.is_valid():
        date_from = request.POST.get('date_from')
        date_to = request.POST.get('date_to')
        result = most_availed_treatment(date_from, date_to)
        return render(request, 'generate_report.html', {'form': form, 'result': result})

    return render(request, 'reports.html', {'form': form})


def patient_list_report(request):
    form = PatientDateRangeForm(request.POST or None)
    if form.is_valid():
        date_from = request.POST.get('date_from')
        date_to = request.POST.get('date_to')
        patients = get_patients(date_from, date_to)
        return render(request, 'patient_list_report.html', {'form': form, 'patients': patients})

    return render(request, 'reports.html', {'form': form})


def treatment_list_report(request):
    form = TreatmentDateRangeForm(request.POST or None)
    if form.is_valid():
        date_from = request.POST.get('date_from')
        date_to = request.POST.get('date_to')
        treatments = get_treatments(date_from, date_to)
        return render(request, 'treatment_list_report.html', {'form': form, 'treatments': treatments})

    return render(request, 'reports.html', {'form': form})


def canceled_appointment_report(request):
    form = CancelDateRangeForm(request.POST or None)
    if form.is_valid():
        date_from = request.POST.get('date_from')
        date_to = request.POST.get('date_to')
        canceled_appointment = get_canceled_appointment(date_from, date_to)
        return render(request, 'canceled_appointment_list_report.html', {'form': form, 'canceled_appointment': canceled_appointment})

    return render(request, 'reports.html', {'form': form})


def total_sales(request):
    form = SalesDateRangeForm(request.POST or None)
    if form.is_valid():
        date_from = request.POST.get('date_from')
        date_to = request.POST.get('date_to')
        total_sales = total_sales_report(date_from, date_to)
        return render(request, 'total_sales_report.html', {'form': form, 'total_sales': total_sales})

    return render(request, 'reports.html', {'form': form})

reports/templates/canceled_appointment_list_report.html
{% extends 'base.html' %}
{% block title %} Reports {% endblock title %}
{% block page_title %} Reports

<button onclick="printReport()" class="btn btn-outline-info btn-sm" style="float:right">
    <i class="fas fa-arrow-circle-down"></i> Download</button>

{% endblock page_title %}

{% block content %}

<!-- Main content -->
<section class="content" xmlns="">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="col-12">
            <div class="card card-outline card-primary">
                <div class="card-header">
                    <h3 class="card-title">List of Canceled Appointment</h3>
                </div>
                <!-- /.card-header -->
                  <div class="card-body">
                      <h6>Date Range: {{ form.cleaned_data.date_from }} to {{ form.cleaned_data.date_to }}</h6>
                  <table id="canceled-table" class="table">
                     <thead>
                        <tr>
                            <th>NAME</th>
                            <th>TREATMENT</th>
                            <th>DATE</th>
                            <th>TIME</th>
                        </tr>
                     </thead>
                     <tbody>
                        {% for appointment in canceled_appointment %}
                        <tr>
                            <td>{{ appointment.user.first_name }} {{ appointment.user.last_name }}</td>
                            <td>{{ appointment.treatment }}</td>
                            <td>{{ appointment.date }}</td>
                            <td>{{ appointment.time }}</td>
                        </tr>
                        {% endfor %}
                     </tbody>
                  </table>
               </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>

    <!-- /.container-fluid -->
</section>
<!-- /.content -->

{% endblock content %} {% block script %}
<!--<script>-->
<!--  $(function () {-->
<!--    $('#canceled-table').DataTable({-->
<!--      "paging": true,-->
<!--      "lengthChange": false,-->
<!--      "searching": false,-->
<!--      "ordering": false,-->
<!--      "info": true,-->
<!--      "autoWidth": false,-->
<!--      "responsive": true,-->
<!--      "pageLength": 20,-->
<!--    });-->
<!--  });-->
<!--</script>-->
<script>
    function printReport() {
        // Open the print dialog
        window.print();
    }
</script>
{% endblock script %}

reports/templates/generate_report.html
{% extends 'base.html' %}
{% block title %} Reports {% endblock title %}
{% block page_title %} Reports
 <button onclick="printReport()" class="btn btn-outline-info btn-sm" style="float:right">
                            <i class="fas fa-arrow-circle-down"></i> Download</button>
{% endblock page_title %}
{% block content %}

<!-- Main content -->
<section class="content" xmlns="">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="col-12">
            <div class="card card-outline card-primary">
                <div class="card-header">
                    <h3 class="card-title">Most Availed Treatment by Appointment</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <h6>Date Range: {{ form.cleaned_data.date_from }} to {{ form.cleaned_data.date_to }}</h6>

                    <table id="reports-table" class="table table-striped projects">
                        <tr>
                            <th>Treatment</th>
                            <th>Frequency</th>
                        </tr>
                        {% for entry in result %}
                        <tr>
                            <td>{{ entry.treatment_name }}</td>
                            <td>{{ entry.count }}</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>

    <!-- /.container-fluid -->
</section>
<!-- /.content -->

{% endblock content %} {% block script %}
<script>
    function printReport() {
        // Open the print dialog
        window.print();
    }
</script>
{% endblock script %}

reports/templates/patient_list_report.html
{% extends 'base.html' %}
{% block title %} Reports {% endblock title %}
{% block page_title %} Reports

<button onclick="printReport()" class="btn btn-outline-info btn-sm" style="float:right">
    <i class="fas fa-arrow-circle-down"></i> Download</button>

{% endblock page_title %}

{% block content %}

<!-- Main content -->
<section class="content" xmlns="">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="col-12">
            <div class="card card-outline card-primary">
                <div class="card-header">
                    <h3 class="card-title">List of Patients with Available Points</h3>
                </div>
                <!-- /.card-header -->
                  <div class="card-body">
                      <h6>Date Range: {{ form.cleaned_data.date_from }} to {{ form.cleaned_data.date_to }}</h6>
                  <table id="patient-table" class="table">
                     <thead>
                        <tr>
                            <th>NAME</th>
                            <th>POINTS</th>
                        </tr>
                     </thead>
                     <tbody>
                        {% for patient in patients %}
                        <tr>
                            <td>{{ patient.first_name }} {{ patient.last_name }}</td>
                            <td>{{ patient.userprofile.total_points }}</td>
                        </tr>
                        {% endfor %}
                     </tbody>
                  </table>
               </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>

    <!-- /.container-fluid -->
</section>
<!-- /.content -->

{% endblock content %} {% block script %}
<!--<script>-->
<!--  $(function () {-->
<!--    $('#patient-table').DataTable({-->
<!--      "paging": true,-->
<!--      "lengthChange": false,-->
<!--      "searching": false,-->
<!--      "ordering": false,-->
<!--      "info": true,-->
<!--      "autoWidth": false,-->
<!--      "responsive": true,-->
<!--      "pageLength": 20,-->
<!--    });-->
<!--  });-->
<!--</script>-->
<script>
    function printReport() {
        // Open the print dialog
        window.print();
    }
</script>
{% endblock script %}

reports/templates/reports.html
{% extends 'base.html' %} {% block title %} Reports {% endblock title %} {% block page_title %} Reports {% endblock page_title %} {% block content %}

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                {% if messages %}
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                    {% for message in messages %}
                    <span class="lh-1">{{ message }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
        <div class="row">
              <div class="col-6">
                 <div class="card card-outline card-info">
                    <div class="card-header">
                        <h3 class="card-title">List of Treatments</h3>
                    </div>
                    <form class="form-horizontal" action="{% url 'reports:treatment_list_report' %}" method="POST">
                        <div class="card-body">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="">Date from:</label>
                                <div class="col-md-4">
                                    <input type="date" name="date_from" id="treatment_date_from" required value="{{ form.cleaned_data.date_from|default:'' }}" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="">Date to:</label>
                                <div class="col-md-12">
                                    <input type="date" name="date_to" id="treatment_date_to" required value="{{ form.cleaned_data.date_to|default:'' }}" />
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-info">Generate Report</button>
                        </div>
                    </form>
                </div>
              </div>

              <div class="col-6">
                <div class="card card-outline card-info">
                    <div class="card-header">
                        <h3 class="card-title">List of Patients with Availble Points</h3>
                    </div>
                    <form class="form-horizontal" action="{% url 'reports:patient_list_report' %}" method="POST">
                        <div class="card-body">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="">Date from:</label>
                                <div class="col-md-4">
                                    <input type="date" name="date_from" id="patient_date_from" required value="{{ form.cleaned_data.date_from|default:'' }}" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="">Date to:</label>
                                <div class="col-md-12">
                                    <input type="date" name="date_to" id="patient_date_to" required value="{{ form.cleaned_data.date_to|default:'' }}" />
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-info">Generate Report</button>
                        </div>
                    </form>
                </div>
              </div>
        </div>

        <div class="row">
              <div class="col-6">
                  <div class="card card-outline card-info">
                    <div class="card-header">
                        <h3 class="card-title">Most Availed Treatment by Appointment</h3>
                    </div>
                    <form class="form-horizontal" action="{% url 'reports:appointment_report' %}" method="POST">
                        <div class="card-body">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="">Date from:</label>
                                <div class="col-md-4">
                                    <input type="date" name="date_from" id="id_date_from" required value="{{ form.cleaned_data.date_from|default:'' }}" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="">Date to:</label>
                                <div class="col-md-12">
                                    <input type="date" name="date_to" id="id_date_to" required value="{{ form.cleaned_data.date_to|default:'' }}" />
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-info">Generate Report</button>
                        </div>
                    </form>
                </div>
              </div>

              <div class="col-6">
                <div class="card card-outline card-info">
                    <div class="card-header">
                        <h3 class="card-title">Total Sales</h3>
                    </div>
                    <form class="form-horizontal" action="{% url 'reports:total_sales' %}" method="POST">
                        <div class="card-body">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="">Date from:</label>
                                <div class="col-md-4">
                                    <input type="date" name="date_from" id="sales_date_from" required value="{{ form.cleaned_data.date_from|default:'' }}" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="">Date to:</label>
                                <div class="col-md-12">
                                    <input type="date" name="date_to" id="sales_date_to" required value="{{ form.cleaned_data.date_to|default:'' }}" />
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-info">Generate Report</button>
                        </div>
                    </form>
                </div>
            </div>
              </div>
        </div>

        <div class="row">
              <div class="col-6">
                    <div class="card card-outline card-info">
                    <div class="card-header">
                        <h3 class="card-title">List of Canceled Appointment</h3>
                    </div>
                    <form class="form-horizontal" action="{% url 'reports:canceled_appointment_report' %}" method="POST">
                        <div class="card-body">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="">Date from:</label>
                                <div class="col-md-4">
                                    <input type="date" name="date_from" id="canceled_date_from" required value="{{ form.cleaned_data.date_from|default:'' }}" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="">Date to:</label>
                                <div class="col-md-12">
                                    <input type="date" name="date_to" id="canceled_date_to" required value="{{ form.cleaned_data.date_to|default:'' }}" />
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-info">Generate Report</button>
                        </div>
                    </form>
                </div>
              </div>

              <div class="col-6">

              </div>
        </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

    <!-- /.container-fluid -->
</section>
<!-- /.content -->

{% endblock content %} {% block script %}
<script>
    setInterval(function () {
        window.location.reload();
    }, 60000); // refresh every 1 min
</script>

<script>
    function printReport() {
        // Open the print dialog
        window.print();
    }
</script>
{% endblock script %}

reports/templates/total_sales_report.html
{% extends 'base.html' %}
{% block title %} Reports {% endblock title %}
{% block page_title %} Reports

<button onclick="printReport()" class="btn btn-outline-info btn-sm" style="float:right">
    <i class="fas fa-arrow-circle-down"></i> Download</button>

{% endblock page_title %}

{% block content %}

<!-- Main content -->
<section class="content" xmlns="">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="col-12">
            <div class="card card-outline card-primary">
                <div class="card-header">
                    <h3 class="card-title">Total Sales Report</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <h6>Date Range: {{ form.cleaned_data.date_from }} to {{ form.cleaned_data.date_to }}</h6>
                    <p><b>Total Sales: <span>&#8369;</span>{{ total_sales }}</b></p>
               </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>

    <!-- /.container-fluid -->
</section>
<!-- /.content -->

{% endblock content %} {% block script %}

<script>
    function printReport() {
        // Open the print dialog
        window.print();
    }
</script>
{% endblock script %}

reports/templates/treatment_list_report.html
{% extends 'base.html' %}
{% block title %} Reports {% endblock title %}
{% block page_title %} Reports

<button onclick="printReport()" class="btn btn-outline-info btn-sm" style="float:right">
    <i class="fas fa-arrow-circle-down"></i> Download</button>

{% endblock page_title %}

{% block content %}

<!-- Main content -->
<section class="content" xmlns="">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="col-12">
            <div class="card card-outline card-primary">
                <div class="card-header">
                    <h3 class="card-title">List of Treatment</h3>
                </div>
                <!-- /.card-header -->
                  <div class="card-body">
                      <h6>Date Range: {{ form.cleaned_data.date_from }} to {{ form.cleaned_data.date_to }}</h6>
                  <table id="treatment-table" class="table">
                     <thead>
                        <tr>
                            <th>TREATMENT</th>
                        </tr>
                     </thead>
                     <tbody>
                        {% for treatment in treatments %}
                        <tr>
                            <td>{{ treatment.name }}</td>
                        </tr>
                        {% endfor %}
                     </tbody>
                  </table>
               </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>

    <!-- /.container-fluid -->
</section>
<!-- /.content -->

{% endblock content %} {% block script %}
<!--<script>-->
<!--  $(function () {-->
<!--    $('#treatment-table').DataTable({-->
<!--      "paging": true,-->
<!--      "lengthChange": false,-->
<!--      "searching": false,-->
<!--      "ordering": false,-->
<!--      "info": true,-->
<!--      "autoWidth": false,-->
<!--      "responsive": true,-->
<!--      "pageLength": 20,-->
<!--    });-->
<!--  });-->
<!--</script>-->
<script>
    function printReport() {
        // Open the print dialog
        window.print();
    }
</script>
{% endblock script %}