config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from loyalty_app.views import process_login
from user_profile.views import process_admin_login

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', process_admin_login, name='login'),
    path('', process_login, name='loyalty_login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('/logout/', auth_views.LogoutView.as_view(next_page='loyalty_login'), name='loyalty_logout'),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    path('users/', include('user_profile.urls'), name='users'),
    path('treatments/', include('treatments.urls'), name='treatments'),
    path('patients/', include('patients.urls'), name='patients'),
    path('appointments/', include('appointments.urls'), name='appointments'),
    path('', include('loyalty_app.urls'), name='loyalty'),
    path('transactions/', include('transactions.urls'), name='transactions'),
    path('redeem_points/', include('redeem_points.urls'), name='redeem_points'),
    path('offers/', include('offers.urls'), name='offers'),
    path('reports/', include('reports.urls'), name='reports'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_profile/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    # profile
    path('', views.profile_list, name='list'),
    path('create/', views.profile_create, name='create'),
    path('<int:pk>/edit/', views.user_profile_edit, name='edit'),
    path('<int:pk>/disable/', views.profile_disable, name='disable'),
    path('edit-profile/', views.my_profile_edit, name='my_profile_edit'),
    # edit password
    path('<int:pk>/edit/password/', views.admin_edit_password, name='admin_password_update'),
    path('profile/edit/password/', views.profile_edit_password, name='own_profile_edit_password'),
    # group
    path('group/list/', views.group_list, name='group_list'),
    path('group/create/', views.group_create, name='group_create'),
    path('group/<int:pk>/create/', views.group_edit, name='group_edit'),

]

user_profile/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.forms import ModelForm, NumberInput
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import Group, Permission
from django.contrib.auth.forms import (
    UserCreationForm, UserChangeForm, AdminPasswordChangeForm
)

from user_profile.models import UserProfile

User = get_user_model()


#
# class LoginForm(AuthenticationForm):
#
#     username = forms.CharField(  # This is always 'username'
#         max_length=100,
#         widget=forms.TextInput(
#             attrs={
#                 'class': 'form-control',
#                 'name': 'email',
#                 'placeholder': 'Email'}
#         )
#     )
#     password = forms.CharField(
#         max_length=100,
#         widget=forms.PasswordInput(
#             attrs={
#                 'class': 'form-control',
#                 'name': 'password',
#                 'placeholder': 'Password'}
#         )
#     )


class ProfileCreationForm(UserCreationForm):
    group = forms.ModelChoiceField(
        queryset=Group.objects.all(),
        widget=forms.Select(
            attrs={'class': 'form-control'}
        )
    )
    email = forms.EmailField(
        max_length=200,
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    password1 = forms.CharField(
        max_length=100,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control'}
        )
    )
    password2 = forms.CharField(
        max_length=100,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control'}
        )
    )
    first_name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        ),
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z\s]*$',
                message='Firstname must be letters only'),
        ],
    )
    last_name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        ),
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z\s]*$',
                message='Lastname must be letters only'),
        ],
    )
    mobile = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'name': 'mobile'}
        ),
        validators=[
            RegexValidator(
                regex=r'^09\d{9}$',
                message="Phone number must be in format 09123456789"
            )
        ]
    )
    is_active = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class': 'form-check-input',
            }),
        initial=True
    )

    class Meta:
        model = User
        fields = (
            'email',
            'password1',
            'password2',
            'first_name',
            'last_name',
            'mobile',
            'is_active',
        )

    def save(self, commit=True):
        user = super(ProfileCreationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.mobile = self.cleaned_data['mobile']

        if commit:
            user.save()
            user.groups.clear()
            user.groups.add(self.cleaned_data['group'])

        return user


class EditProfileForm(UserChangeForm):
    group = forms.ModelChoiceField(
        queryset=Group.objects.all(),
        widget=forms.Select(
            attrs={
                'class': 'form-control'})
    )
    first_name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'})
    )
    last_name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'})
    )
    email = forms.EmailField(
        max_length=200,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'})
    )
    mobile = forms.CharField(
        max_length=100,
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'}),
        validators=[
            RegexValidator(
                regex=r'^09\d{9}$',
                message="Phone number must be in format 09123456789"
            )
        ]
    )
    is_active = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class': 'form-check-input',
            })
    )

    class Meta:
        model = User
        fields = (
            'password',
            'first_name',
            'last_name',
            'email',
            'mobile',
            'is_active',
        )


class UserProfileEdit(ModelForm):
    mobile = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'name': 'mobile'}
        ),
        validators=[
            RegexValidator(
                regex=r'^09\d{9}$',
                message="Phone number must be in format 09123456789"
            )
        ]
    )
    email = forms.EmailField(
        max_length=200,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'})
    )

    class Meta:
        model = User
        fields = (
            'mobile',
            'email',
        )


class AdminEditPasswordForm(AdminPasswordChangeForm):
    password1 = forms.CharField(max_length=100,
                                widget=forms.PasswordInput(
                                    attrs={
                                        'class': 'form-control'}))
    password2 = forms.CharField(max_length=100,
                                widget=forms.PasswordInput(
                                    attrs={
                                        'class': 'form-control'}))

user_profile/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.http import HttpResponseRedirect
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Permission, Group
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import (
    LoginRequiredMixin, PermissionRequiredMixin
)

from user_profile.forms import ProfileCreationForm, EditProfileForm, AdminEditPasswordForm, UserProfileEdit
from .decorators import admin_required

User = get_user_model()


def process_admin_login(request):
    if request.method == 'POST':
        username = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user is not None:
            if not user.is_patient and user.is_active:
                login(request, user)
                return redirect('dashboard:main')
            else:
                messages.error(request, "Sorry, you are not allowed to access this page.")
                return render(request, 'auth_login.html')
        else:
            messages.error(request, "Your username and password didn't match. Please try again.")
            return render(request, 'auth_login.html')

    return render(request, 'auth_login.html')


@login_required
@admin_required
@permission_required('user_profile.view_user', raise_exception=True)
def profile_list(request):
    users = User.objects.filter(is_patient=False).order_by('-created_at')
    template_name = 'user_list.html'
    context = {'users': users}
    return render(request, template_name, context)


@login_required
@admin_required
@permission_required('user_profile.add_user', raise_exception=True)
def profile_create(request):
    form = ProfileCreationForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        user.is_staff = True
        user.save()
        uid = User.objects.get(id=user.id)
        uid.save()
        messages.success(request, 'User created successfully.')
        return redirect('/users')

    template_name = 'user_create.html'
    context = {'form': form}
    return render(request, template_name, context)


@login_required
@admin_required
@permission_required('user_profile.change_user', raise_exception=True)
def my_profile_edit(request):
    user = get_object_or_404(User, id=request.user.id)
    form = UserProfileEdit(request.POST or None, instance=request.user)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Profile updated successfully.')
        return redirect('users:my_profile_edit')

    template_name = 'my_profile_edit.html'
    context = {'form': form, 'user_profile': user}
    return render(request, template_name, context)


@login_required
@admin_required
@permission_required('user_profile.change_user', raise_exception=True)
def user_profile_edit(request, pk):
    user = get_object_or_404(User, id=pk)
    group = Group.objects.filter(user=user).first()
    form = EditProfileForm(request.POST or None, instance=user, initial={'group': group})
    if form.is_valid():
        user_edit = form.save(commit=False)
        user_edit.is_active = True
        user_edit.save()
        user.groups.clear()
        user.groups.add(request.POST['group'])
        messages.success(request, 'Users updated successfully.')
        return redirect('users:edit', pk)

    template_name = 'user_edit.html'
    context = {'form': form, 'user_profile': user}
    return render(request, template_name, context)


@login_required
@admin_required
@permission_required('user_profile.disable_user', raise_exception=True)
def profile_disable(request, pk):
    users = get_object_or_404(User, id=pk)
    users.is_active = False
    users.save()
    messages.success(request, 'Users has been disabled.')
    return redirect('/users')


@login_required
@admin_required
@permission_required('auth.view_group', raise_exception=True)
def group_list(request):
    group_list = Group.objects.all()
    template = 'group_list.html'
    context = {'group_list': group_list}
    return render(request, template, context)


@login_required
@admin_required
@permission_required('auth.add_group', raise_exception=True)
def group_create(request):
    if request.method == 'POST':
        permissions = request.POST.getlist('permission')
        new_group, group = Group.objects.get_or_create(
            name=request.POST['group_name']
        )
        new_group.permissions.set(permissions)
        return redirect('users:group_list')
    else:
        permission = Permission.objects.all()
        template = 'group_create.html'
    context = {
        'permission': permission
    }
    return render(request, template, context)


@login_required
@admin_required
@permission_required('auth.change_group', raise_exception=True)
def group_edit(request, pk):
    if request.method == 'GET':
        group = Group.objects.get(id=pk)
        group_permission = Permission.objects.filter(group__id=group.id)
        permission = Permission.objects.exclude(group__id=group.id)
    else:
        permissions = request.POST.getlist('permission')
        group = Group.objects.get(id=pk)
        obj, created = Group.objects.update_or_create(
            name=group,
            defaults={'name': request.POST['group_name']},
        )
        obj.permissions.set(permissions)
        return redirect('users:group_list')

    template = 'group_edit.html'
    context = {
        'group': group,
        'permission': permission,
        'group_permission': group_permission
    }
    return render(request, template, context)


@login_required
@admin_required
def admin_edit_password(request, pk):
    user = get_object_or_404(User, id=pk)
    form = AdminEditPasswordForm(data=request.POST or None, user=user)
    if form.is_valid():
        form.save()
        messages.success(request, 'Password changed successfully.')
        return redirect('users:edit', pk)
    template_name = 'user_admin_edit_password.html'
    context = {'form': form}
    return render(request, template_name, context)


@login_required
@admin_required
def profile_edit_password(request):
    user = get_object_or_404(User, id=request.user.id)
    form = AdminEditPasswordForm(data=request.POST or None, user=user)
    if form.is_valid():
        form.save()
        return redirect('/admin')

    template_name = 'user_profile_edit_password.html'
    context = {'form': form}
    return render(request, template_name, context)

user_profile/templates/group_edit.html
{% extends "base.html" %}

{% block page_title %} Group {% endblock page_title %}


{% block content %}

<!-- Main content -->
<section class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-12">
            <div class="card card-outline card-info">
               <div class="card-header">
                  <h3 class="card-title">Edit Group</h3>
               </div>
               <!-- /.card-header -->
               <form class="form-horizontal" id="frm" method="POST" enctype="multipart/form-data" action="{% url 'users:group_edit' group.id %}" novalidate>
                  <div class="card-body">
                     {% csrf_token %}
                     <div class="form-group">
                          <label for="" class="control-label">Group Name:</label>
                          <div class="col-md-4">
                               <input name="group_name" value="{{group.name}}" type="textbox" class="form-control" />
                          </div>
                     </div>

                     <div class="form-group">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label">Permissions:</label>
                                    <select id="sbPermission" class="form-control" multiple="multiple" style="height: 250px; margin-left:8px"></select>
                                    <div style="margin: 10px -9px 0 9px;">
                                        <button type="button" id="btnAll" class="btn btn-primary btn-block"><i class="fas fa-solid fa-arrow-right"></i></button>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-1" valign="bottom">
                                <div style="margin-top: calc(50% + 60px); margin-left: 30px;">
                                    <button type="button" id="btnChoose" class="btn btn-block bg-gradient-primary btn-sm"><i class="fas fa-solid fa-arrow-right"></i></button>
                                    <br>
                                    <button type="button" id="btnRemove"  class="btn btn-block bg-gradient-primary btn-sm"><i class="fas fa-solid fa-arrow-left"></i></button>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label class="control-label" ></label>
                                    <select class="form-control" id="permission" name="permission" multiple="multiple" style="height: 250px; margin: 8px 0 0 20px">
                                    </select>
                                </div>
                            </div>
                        </div>
                     </div>
                  </div>
                     <div class="card-footer">
                         <button type="submit" class="btn btn-info">Save</button>
                     </div>
               </form>
               <!-- /.card-body -->
            </div>
         </div>
         <!-- /.col -->
      </div>
      <!-- /.row -->
   </div>
   <!-- /.container-fluid -->
</section>
<!-- /.content -->

{% endblock content %}

{% block script %}
<script>
  $(document).ready(function(){
    var permission_id = [
      {% for data in permission %}
        `{{data.id}}`,
      {% endfor %}
    ],permission_title = [
      {% for data in permission %}
        `{{data}}`,
      {% endfor %}
    ],group_id = [
      {% for data in group_permission %}
        `{{data.id}}`,
      {% endfor %}
    ],group_name = [
      {% for data in group_permission %}
        `{{data}}`,
      {% endfor %}
    ]

    $(permission_id).each(function(key, value){

      $('#sbPermission').append(`<option value="${value}">${permission_title[key]}</option>`);

    });//end of permission list

    $(group_id).each(function(key, value){

      $('#permission').append(`<option value="${value}">${group_name[key]}</option>`);

    });//end of each


    $('#btnChoose').click(function(){

      $('#sbPermission :selected').each(function(){

        $('#permission').append(`<option value="${$(this).val()}">${$(this).html()}</option>`);

        $(this).remove();

      });//end of each

    });//end of btnChoose

    $('#btnRemove').click(function(){

      $('#permission :selected').each(function(){

        $('#sbPermission').append(`<option value="${$(this).val()}">${$(this).html()}</option>`);

        $(this).remove();

      });//end of each


    });//end of btnRemove

    $('#btnAll').click(function(){

      $('#sbPermission option').each(function(){

          $('#permission').append(`<option value="${$(this).val()}">${$(this).html()}</option>`);

          $(this).remove();

      });//end of each

    });//end of btnAll

    $('#frm').on("submit", function(e){

      // selected_permission = $('#permission option').length

      // if(selected_permission == 0){

      //   $('#sbPermission option').each(function(){

      //     $('#permission').append(`<option value="${$(this).val()}" selected="selected">${$(this).html()}</option>`);

      //   });
      // }

      // else{


      // }
      $('#permission option').each(function(key,val){

          $(this).prop('selected',true)

      });//end of each option

    });//end of submit



  });
</script>

{% endblock script %}

user_profile/templates/group_list.html
{% extends "base.html" %}
{% block title %} Group {% endblock %}
{% block page_title %} Group List {% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
           <div class="col-12">
               {% if messages %}
                <div class="alert alert-success alert-dismissible">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                  {% for message in messages %}
                    <span class="lh-1">{{ message }}</span>
                  {% endfor %}
                </div>
                {% endif %}
           </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card card-outline card-primary">
				   <div class="card-header">
					  <h3 class="card-title">Group List</h3>
					  <div class="card-tools">
						 <a href="{% url 'users:group_create' %}" class="btn btn-sm btn-block bg-gradient-success">
							Add Group
						 </a>
					  </div>
				   </div>
                   <div class="card-body">
                       <table id="group-table" class="table table-striped projects">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Group</th>
                                    <th>ACTIONS</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for group in group_list %}
                                <tr>
                                    <th>{{group.id}}</th>
                                    <td>{{group.name}}</td>
                                    <td>
                                        <a href="{% url 'users:group_edit' group.id %}" class="pull-right text-blue"><i class="fas fa-pencil-alt"></i></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                       </table>
                   </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

{% block script %}
    <script>
      $(function () {
        $('#group-table').DataTable({
          'paging'      : true,
          'lengthChange': false,
          'searching'   : true,
          'ordering'    : false,
          'info'        : true,
          'autoWidth'   : false,
          "order": [[ 0, "desc" ]]
        })
      })
    </script>
{% endblock script %}

user_profile/templates/my_profile_edit.html
{% extends "base.html" %}
{% block title %} Profile {% endblock %}
{% block page_title %} Profile {% endblock page_title %}


{% block content %}

<!-- Main content -->
<section class="content">
   <div class="container-fluid">
       <div class="row">
			   <div class="col-12">
				   {% if messages %}
					<div class="alert alert-success alert-dismissible">
					  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
					  {% for message in messages %}
						<span class="lh-1">{{ message }}</span>
					  {% endfor %}
					</div>
					{% endif %}
			   </div>
		   </div>
      <div class="row">
         <div class="col-12">
            <div class="card card-outline card-info">
               <div class="card-header">
                  <h3 class="card-title">Edit Profile</h3>
               </div>
               <!-- /.card-header -->
                  <form class="form-horizontal" method="POST" novalidate>
                  <div class="card-body">
                     {% csrf_token %}
<!--                     <div class="form-group ">-->
<!--                        <label for="" class="control-label">Group:</label>-->
<!--                        <div class="col-md-4">-->
<!--                           {% for group in user.groups.all %}-->
<!--                              <input type="text" name="group" value="{{ group.name }}" class="form-control" maxlength="100" readonly="readonly">-->
<!--                           {% endfor %}-->
<!--                           <span class="help-block"></span>-->
<!--                        </div>-->
<!--                     </div>-->
                     <div class="form-group ">
                        <label for="" class="control-label">First Name:</label>
                        <div class="col-md-4">
                            <input type="text" name="first_name" value="{{ user_profile.first_name }}" class="form-control" maxlength="100" readonly="readonly">
                            <span class="help-block"></span>
                        </div>
                     </div>
                     <div class="form-group">
                        <label for="" class="control-label">Last Name:</label>
                        <div class="col-md-4">
                            <input type="text" name="last_name" value="{{ user_profile.last_name }}" class="form-control" maxlength="100" readonly="readonly">
                            <span class="help-block"></span>
                        </div>
                     </div>
                     <div class="form-group">
                        <label for="" class="control-label">Mobile Phone:</label>
                        <div class="col-md-4">
                           {{ form.mobile }}
                           <span class="help-block">{{ form.mobile.errors }}</span>
                        </div>
                     </div>
                     <div class="form-group">
                        <label for="" class="control-label">Email:</label>
                        <div class="col-md-4">
                           {{ form.email }}
                           <span class="help-block">{{ form.email.errors }}</span>
                        </div>
                     </div>
                      <div class="form-group">
                         <div class="col-md-4">
                             <a href="{% url 'users:own_profile_edit_password' %}"><p class="text-right">Change password</p> </a>
                         </div>
                     </div>
                  </div>
                  <div class="card-footer">
                     <button type="submit" class="btn btn-info">Save</button>
                  </div>
               </form>
               <!-- /.card-body -->
            </div>
         </div>
         <!-- /.col -->
      </div>
      <!-- /.row -->
   </div>
   <!-- /.container-fluid -->
</section>
<!-- /.content -->

{% endblock content %}

{% block script %}

{% endblock script %}

user_profile/templates/user_list.html
{% extends "base.html" %}
{% block title %} System User {% endblock %}
{% block page_title %} System Users {% endblock page_title %}


{% block content %}

<!-- Main content -->
<section class="content">
   <div class="container-fluid">
       <div class="row">
			   <div class="col-12">
				   {% if messages %}
					<div class="alert alert-success alert-dismissible">
					  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
					  {% for message in messages %}
						<span class="lh-1">{{ message }}</span>
					  {% endfor %}
					</div>
					{% endif %}
			   </div>
		   </div>
      <div class="row">
         <div class="col-12">
            <div class="card card-outline card-primary">
               <div class="card-header">
                  <h3 class="card-title">System User List</h3>
                  <div class="card-tools">
                     <a href="{% url 'users:create' %}" class="btn btn-sm btn-block bg-gradient-success">
                        Add User
                     </a>
                  </div>
               </div>
               <!-- /.card-header -->
               <div class="card-body">
                  <table id="users-table" class="table table-striped projects">
                     <thead>
                        <tr>
<!--                            <th>USER ID</th>-->
                            <th>USER GROUP</th>
                            <th>FIRST NAME</th>
                            <th>LAST NAME</th>
                            <th>MOBILE #</th>
                            <th>EMAIL ADDRESS</th>
                            <th>STATUS</th>
                            <th>ACTIONS</th>
                        </tr>
                     </thead>
                     <tbody>
                        {% for user in users %}
                        <tr>
<!--                            <th>{{ user.id }}</th>-->
                            <td>
                                {% for group in user.groups.all %}
                                    {{ group.name }}
                                {% endfor %}
                            </td>
                            <td>{{ user.first_name }}</td>
                            <td>{{ user.last_name }}</td>
                            <td>{{ user.mobile }}</td>
                            <td>{{ user.email}}</td>
                            <td>
                                {% if user.is_active %}
                                    <span class="badge bg-success">Active</span>
                                {% else %}
                                    <span class="badge bg-danger">Inactive</span>
                                {% endif %}
                            </td>
                            <td>
                                <a href="{% url 'users:edit' user.id %}" class="pull-right text-blue mr-3"><i class="fas fa-pencil-alt"></i></a>
                                {% if not user.is_superuser %}
                                    <a href="{% url 'users:disable' user.id %}" class="pull-right text-red"><i class="fas fa-ban"></i></a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                     </tbody>
                  </table>
               </div>
               <!-- /.card-body -->
            </div>
         </div>
         <!-- /.col -->
      </div>
      <!-- /.row -->
   </div>
   <!-- /.container-fluid -->
</section>
<!-- /.content -->

{% endblock content %}

{% block script %}
    <script>
      $(function () {
        $('#users-table').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": true,
          "ordering": false,
          "info": true,
          "autoWidth": false,
          "responsive": true,
          "pageLength": 10,
        });
      });
    </script>
{% endblock script %}