config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from loyalty_app.views import process_login
from user_profile.views import process_admin_login

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', process_admin_login, name='login'),
    path('', process_login, name='loyalty_login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('/logout/', auth_views.LogoutView.as_view(next_page='loyalty_login'), name='loyalty_logout'),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    path('users/', include('user_profile.urls'), name='users'),
    path('treatments/', include('treatments.urls'), name='treatments'),
    path('patients/', include('patients.urls'), name='patients'),
    path('appointments/', include('appointments.urls'), name='appointments'),
    path('', include('loyalty_app.urls'), name='loyalty'),
    path('transactions/', include('transactions.urls'), name='transactions'),
    path('redeem_points/', include('redeem_points.urls'), name='redeem_points'),
    path('offers/', include('offers.urls'), name='offers'),
    path('reports/', include('reports.urls'), name='reports'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='main'),
]

offers/urls.py
from config.urls import path
from . import views


app_name = 'offers'

urlpatterns = [
    path('list', views.offer_list, name='offer_list'),
    path('create', views.offer_create, name='offer_create'),
    path('<int:pk>/edit', views.offer_edit, name='offer_edit'),
    path('<int:pk>/disable', views.offer_disable, name='offer_disable'),
    path('offer-list', views.offer_list_loyalty, name='offer_list_loyalty'),

]

patients/urls.py
from django.urls import path
from . import views

app_name = 'patients'

urlpatterns = [

    # patient
    path('list', views.patient_list, name='patient_list'),
    path('create/', views.patient_create, name='patient_create'),
    path('<int:pk>/edit/', views.patient_edit, name='patient_edit'),
    path('<int:pk>/disable/', views.patient_disable, name='patient_disable'),
    path('<int:pk>/patient-information', views.patient_info, name='patient_info'),
    path('<int:pk>/patient-renewal', views.patient_renewal, name='patient_renewal'),
    path('<int:pk>/patient-profile', views.patient_profile, name='patient_profile'),
    # reset password
    path('<int:pk>/reset/password/', views.reset_password, name='reset_password'),
    path('<int:pk>/generate-password/', views.generate_password, name='generate_password'),
    # change password for patient
    path('change password', views.change_password, name='change_password'),
    # scanner
    path('qr_scan', views.scanner, name='scanner'),
    # scanned patient information
    path('patient-information', views.scanned_patient_info, name='scanned_patient_info'),

]

reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'

urlpatterns = [
    path('report', views.report, name='report'),
    path('appointment-report', views.appointment_report, name='appointment_report'),
    path('patient-list-report', views.patient_list_report, name='patient_list_report'),
    path('treatment-list-report', views.treatment_list_report, name='treatment_list_report'),
    path('canceled-appointment-report', views.canceled_appointment_report, name='canceled_appointment_report'),
    path('total-sales', views.total_sales, name='total_sales'),

]

config/templates/snippets/css.html
{% load static %}

<!-- Font Awesome Icons -->
<link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">

<!-- Bootstrap 4 -->
<link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">

<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">

<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">

<!-- CSS -->
<link rel="stylesheet" href="{% static 'dist/css/simple-notify.min.css'%}">


<!-- Custom CSS -->
<link rel="stylesheet" href="{% static 'dist/css/custom.css' %}">

config/templates/snippets/customer_navbar.html
{% load static %}

<a href="{% url 'loyalty:home' %}" class="navbar-brand">
    <img src="{% static 'dist/img/splendor_logo.png' %}" class="brand-image" alt="Image Logo" width="100%">
</a>
<button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse order-3" id="navbarCollapse">
    <ul class="navbar-nav">
        <li class="nav-item">
             <a href="{% url 'treatments:treatment_list_loyalty' %}" class="nav-link"><p style="font-size:15px">TREATMENTS</p></a>
       </li>
        <li class="nav-item">
            <a href="{% url 'offers:offer_list_loyalty' %}" class="nav-link"><p style="font-size:15px">OFFERS</p></a>
        </li>
        <li class="nav-item">
            <a href="{% url 'transactions:transaction_history' %}" class="nav-link"><p style="font-size:15px">TRANSACTIONS</p></a>
        </li>


        <li class="nav-item">

            <a href="{% url 'appointments:appointment_create' %}" class="nav-link">
                <p style="font-size:15px">BOOK APPOINTMENT</p>
            </a>

        </li>
    </ul>
</div>

<ul class="order-1 order-md-3 navbar-nav navbar-expand ml-auto">
    <li class="nav-item dropdown">
        <a class="nav-link text-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
           aria-expanded="false"><i class="fas fa-user-circle" style="font-size: 30px"></i></a>

        <ul class="dropdown-menu" aria-labelledby="profileDropdown">
            <li><a class="dropdown-item" href="{% url 'patients:patient_profile' user.id %}">Profile</a></li>
            <li>{% if user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'loyalty_logout' %}">Logout</a>
                {% endif %}
            </li>
        </ul>
    </li>
</ul>

config/templates/snippets/footer.html
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
     <b>Version</b> 1.0.0
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2023 <a href="#">AENR</a>.</strong> All rights reserved.
</footer>

config/templates/snippets/js.html
{% load static %}

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html5-qrcode/2.3.4/html5-qrcode.min.js" integrity="sha512-k/KAe4Yff9EUdYI5/IAHlwUswqeipP+Cp5qnrsUjTPCgl51La2/JhyyjNciztD7mWNKLSXci48m7cctATKfLlQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>

<script src="{% static 'plugins/popper/umd/popper.min.js' %}"></script>

<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>

<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>

<script src="{% static 'dist/js/all.min.js' %}"></script>
<script src="{% static 'dist/js/myscript.js' %}"></script>
<script src="{% static 'dist/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'dist/js/script.js' %}"></script>

<!-- Add this in your HTML file -->
<!--<script src="https://cdn.jsdelivr.net/npm/@zxing/library@0.22.0"></script>-->

<!--Chart-->
<script src="{% static 'dist/js/chart.js' %}"></script>

<script src="{% static 'dist/js/html5-qrcode.min.js'%}"></script>

<script src="{% static 'dist/js/instascan.min.js'%}"></script>

<script src="https://js.pusher.com/8.2.0/pusher.min.js"></script>

<script src="{% static 'dist/js/simple-notify.min.js'%}"></script>

config/templates/snippets/navbar.html
{% load static %}
<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'dashboard:main' %}" class="nav-link">Dashboard</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
        <a class="nav-link" href="{% url 'patients:scanner' %}" role="button">
          <i class="fas fa-camera"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
<!-- /.navbar -->

config/templates/snippets/sidebar.html
{% load static %}

<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <div class="image">
            <img src="{% static 'dist/img/blue_logo.png' %}" class="img-circle brand-image-xl logo-xs" alt="Image Logo" >
            <img src="{% static 'dist/img/splendor_logo.png' %}" class="" alt="Image Logo" width="100%">
        </div>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{% static 'dist/img/default-avatar.jpg' %}" class="img-circle elevation-2" alt="User Image" />
            </div>
            <div class="info">
                <a href="#" class="d-block">
                    {% if user.is_authenticated %} {{ user.first_name }} {{ user.last_name }} {% endif %}
                </a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="{% url 'dashboard:main' %}" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                {% if perms.user_profile.view_patient %}
                <li class="nav-item">
                    <a href="{% url 'patients:patient_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p>Patients</p>
                    </a>
                </li>
                {% endif %}

                {% if perms.treatments.view_treatment %}
                <li class="nav-item">
                    <a href="{% url 'treatments:treatment_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-clipboard-list"></i>
                        <p>Treatments</p>
                    </a>
                </li>
                {% endif %}
                {% if perms.appointments.view_appointment %}
                <li class="nav-item">
                    <a href="{% url 'appointments:appointment_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-calendar-check"></i>
                        <p>Appointments</p>
                    </a>
                </li>
                {% endif %}

                {% if perms.user_profile.view_user %}
                <li class="nav-item">
                    <a href="{% url 'users:list' %}" class="nav-link">
                        <i class="nav-icon fas fa-user-cog"></i>
                        <p>System Users</p>
                    </a>
                </li>
                {% endif %}

                {% if perms.offers.view_offer %}
                 <li class="nav-item">
                    <a href="{% url 'offers:offer_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-tag"></i>
                        <p>Offers</p>
                    </a>
                </li>
                {% endif %}

                {% if perms.user_profile.view_user %}
                 <li class="nav-item">
                    <a href="{% url 'reports:report' %}" class="nav-link">
                        <i class="nav-icon fas fa-paste"></i>
                        <p>Reports</p>
                    </a>
                </li>
                {% endif %}

                {% if perms.user_profile.view_user %}
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-cogs"></i>
                        <p>Management<i class="far fas fa-angle-left right"></i></p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <li class="nav-item">
                            <a href="{% url 'users:group_list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>User Groups</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'treatments:service_list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Services</p>
                            </a>
                        </li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>