config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from loyalty_app.views import process_login
from user_profile.views import process_admin_login

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', process_admin_login, name='login'),
    path('', process_login, name='loyalty_login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('/logout/', auth_views.LogoutView.as_view(next_page='loyalty_login'), name='loyalty_logout'),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    path('users/', include('user_profile.urls'), name='users'),
    path('treatments/', include('treatments.urls'), name='treatments'),
    path('patients/', include('patients.urls'), name='patients'),
    path('appointments/', include('appointments.urls'), name='appointments'),
    path('', include('loyalty_app.urls'), name='loyalty'),
    path('transactions/', include('transactions.urls'), name='transactions'),
    path('redeem_points/', include('redeem_points.urls'), name='redeem_points'),
    path('offers/', include('offers.urls'), name='offers'),
    path('reports/', include('reports.urls'), name='reports'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    # services
    path('', views.service_list, name='service_list'),
    path('create/', views.service_create, name='service_create'),
    path('<int:pk>/edit', views.service_edit, name='service_edit'),
    path('<int:pk>/delete', views.service_delete, name='service_delete'),

    # treatment area
    path('areas/', views.area_list, name='area_list'),
    path('area/create/', views.area_create, name='area_create'),
    path('area/<int:pk>/edit', views.area_edit, name='area_edit'),
    path('area/<int:pk>/delete', views.area_delete, name='area_delete'),

    # price type
    path('price-type/', views.price_type_list, name='price_type_list'),
    path('price-type/create/', views.price_type_create, name='price_type_create'),
    path('price-type/<int:pk>/edit', views.price_type_edit, name='price_type_edit'),
    path('<int:pk>/delete', views.price_type_delete, name='price_type_delete'),

    # treatment
    path('treatment/', views.treatment_list, name='treatment_list'),
    path('treatment/create/', views.treatment_create, name='treatment_create'),
    path('treatment/<int:pk>/edit', views.treatment_edit, name='treatment_edit'),
    path('<int:pk>/delete', views.treatment_delete, name='treatment_delete'),
]

treatments/urls.py
from django.urls import path
from . import views

app_name = 'treatments'

urlpatterns = [
    # treatments
    path('', views.service_list, name='service_list'),
    path('create/', views.service_create, name='service_create'),
    path('<int:pk>/edit', views.service_edit, name='service_edit'),
    path('<int:pk>/disable', views.service_disable, name='service_disable'),

    path('treatment-list', views.treatment_list_loyalty, name='treatment_list_loyalty'),

    # treatment
    path('treatment/', views.treatment_list, name='treatment_list'),
    path('treatment/create/', views.treatment_create, name='treatment_create'),
    path('treatment/<int:pk>/edit', views.treatment_edit, name='treatment_edit'),
    path('treatment/<int:pk>/disable', views.treatment_disable, name='treatment_disable'),
]

treatments/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.forms import ModelForm

from .models import Service, Treatment


class ServiceForm(ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'}),
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z\s]*$',
                message='Service name must be letters only'),
        ],
    )

    is_active = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class': 'form-check-input',
            }),
        initial=True

    )

    class Meta:
        model = Service
        fields = ['name', 'is_active']


class TreatmentForm(ModelForm):
    service = forms.ModelChoiceField(
        queryset=Service.objects.exclude(is_active=False),
        widget=forms.Select(
            attrs={
                'class': 'form-control'}),
        error_messages={
            'required': 'Please select a service.',
        },
    )

    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'}),
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z\s]*$',
                message='Treatment name must be letters only'),
        ],
    )

    description = forms.CharField(
        required=False,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows': 5,
            }))

    area = forms.CharField(
         widget=forms.TextInput(
            attrs={
                'class': 'form-control'}),
         validators=[
            RegexValidator(
                regex=r'^[a-zA-Z\s]*$',
                message='Treatment area must be letters only'),
         ],
    )

    type = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'}),
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z\s]*$',
                message='Price type must be letters only'),
        ],
        )

    price = forms.DecimalField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'}),
    )

    is_active = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class': 'form-check-input',
            }),
        initial=True

    )

    class Meta:
        model = Treatment
        fields = [
            'service',
            'name',
            'description',
            'area',
            'type',
            'price',
            'is_active'
        ]

services/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .forms import ServiceForm, TreatmentForm, AreaForm, TypeForm
from .models import Service, Treatment, TreatmentArea, PriceType
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def service_list(request):
    service_list = Service.objects.exclude(status='Deleted')
    template_name = 'services/service_list.html'
    context = {'service_list': service_list}
    return render(request, template_name, context)


@login_required
def service_create(request):
    form = ServiceForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Service created successfully.')
        return redirect('services:service_list')
    template_name = 'services/service_create.html'
    context = {'form': form}
    return render(request, template_name, context)


@login_required
def service_edit(request, pk):
    service = get_object_or_404(Service, id=pk)
    form = ServiceForm(request.POST or None, instance=service)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Service updated successfully.')
        return redirect('services:service_list')
    template_name = 'services/service_edit.html'
    context = {'service': service, 'form': form}
    return render(request, template_name, context)


@login_required
def service_delete(request, pk):
    service = get_object_or_404(Service, id=pk)
    service.status = 'Deleted'
    service.save()
    messages.success(request,
                     'Service has been marked as "Deleted".')
    return redirect('services:service_list')


@login_required
def area_list(request):
    treatment_area_list = TreatmentArea.objects.exclude(status='Deleted')
    template_name = 'services/area_list.html'
    context = {'treatment_area_list': treatment_area_list}
    return render(request, template_name, context)


@login_required
def area_create(request):
    form = AreaForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Treatment area created successfully.')
        return redirect('services:area_list')
    template_name = 'services/area_create.html'
    context = {'form': form}
    return render(request, template_name, context)


@login_required
def area_edit(request, pk):
    treatment_area = get_object_or_404(TreatmentArea, id=pk)
    form = AreaForm(request.POST or None, instance=treatment_area)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Treatment area updated successfully.')
        return redirect('services:area_list')
    template_name = 'services/area_edit.html'
    context = {'area': treatment_area, 'form': form}
    return render(request, template_name, context)


@login_required
def area_delete(request, pk):
    treatment_area = get_object_or_404(TreatmentArea, id=pk)
    treatment_area.status = 'Deleted'
    treatment_area.save()
    messages.success(request, 'Treatment area has been marked as deleted.')
    return redirect('services:area_list')


@login_required
def price_type_list(request):
    pricing_type_list = PriceType.objects.exclude(status='Deleted')
    template_name = 'services/pricetype_list.html'
    context = {'pricing_type_list': pricing_type_list}
    return render(request, template_name, context)


@login_required
def price_type_create(request):
    form = TypeForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Price type created successfully.')
        return redirect('services:price_type_list')
    template_name = 'services/pricetype_create.html'
    context = {'form': form}
    return render(request, template_name, context)


@login_required
def price_type_edit(request, pk):
    price_type = get_object_or_404(PriceType, id=pk)
    form = TypeForm(request.POST or None, instance=price_type)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Price type updated successfully.')
        return redirect('services:price_type_list')
    template_name = 'services/pricetype_edit.html'
    context = {'price_type': price_type, 'form': form}
    return render(request, template_name, context)


@login_required
def price_type_delete(request, pk):
    price_type = get_object_or_404(PriceType, id=pk)
    price_type.status = 'Deleted'
    price_type.save()
    messages.success(request,
                     'Price type has been marked as deleted.')
    return redirect('services:price_type_list')


@login_required
def treatment_list(request):
    treatment_list = Treatment.objects.exclude(status='Deleted')
    template_name = 'services/treatment_list.html'
    context = {'treatment_list': treatment_list}
    return render(request, template_name, context)


@login_required
def treatment_create(request):
    form = TreatmentForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Treatment created successfully.')
        return redirect('services:treatment_list')
    template_name = 'services/treatment_create.html'
    context = {'form': form}
    return render(request, template_name, context)


@login_required
def treatment_edit(request, pk):
    treatment = get_object_or_404(Treatment, id=pk)
    form = TreatmentForm(request.POST or None, instance=treatment)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Treatment created successfully.')
        return redirect('services:treatment_list')
    template_name = 'services/treatment_edit.html'
    context = {'form': form, 'treatment': treatment}
    return render(request, template_name, context)


@login_required
def treatment_delete(request, pk):
    treatment = get_object_or_404(Treatment, id=pk)
    treatment.status = 'Deleted'
    treatment.save()
    messages.success(request,
                     'Treatment has been marked as deleted.')
    return redirect('services:treatment_list')

treatments/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

from user_profile.decorators import admin_required
from .forms import ServiceForm, TreatmentForm
from .models import Service, Treatment
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required


# Create your views here.
@login_required
@admin_required
@permission_required('treatments.view_service', raise_exception=True)
def service_list(request):
    service_list = Service.objects.all().order_by('-created_at')
    template_name = 'treatments/service_list.html'
    context = {'service_list': service_list}
    return render(request, template_name, context)


@login_required
@admin_required
@permission_required('treatments.add_service', raise_exception=True)
def service_create(request):
    form = ServiceForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Service created successfully.')
        return redirect('treatments:service_list')
    template_name = 'treatments/service_create.html'
    context = {'form': form}
    return render(request, template_name, context)


@login_required
@admin_required
@permission_required('treatments.change_service', raise_exception=True)
def service_edit(request, pk):
    service = get_object_or_404(Service, id=pk)
    form = ServiceForm(request.POST or None, instance=service)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Service updated successfully.')
        return redirect('treatments:service_edit',pk)
    template_name = 'treatments/service_edit.html'
    context = {'service': service, 'form': form}
    return render(request, template_name, context)


@login_required
@admin_required
@permission_required('treatments.disable_service', raise_exception=True)
def service_disable(request, pk):
    service = get_object_or_404(Service, id=pk)
    service.is_active = False
    service.save()
    messages.success(request,
                     'Service has been marked as inactive.')
    return redirect('treatments:service_list')


@login_required
@admin_required
@permission_required('treatments.view_treatment', raise_exception=True)
def treatment_list(request):
    treatment_list = Treatment.objects.all().order_by('-created_at')
    template_name = 'treatments/treatment_list.html'
    context = {'treatment_list': treatment_list}
    return render(request, template_name, context)


@login_required
@admin_required
@permission_required('treatments.add_treatment', raise_exception=True)
def treatment_create(request):
    form = TreatmentForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Treatment created successfully.')
        return redirect('treatments:treatment_list')
    template_name = 'treatments/treatment_create.html'
    context = {'form': form}
    return render(request, template_name, context)


@login_required
@admin_required
@permission_required('treatments.change_treatment', raise_exception=True)
def treatment_edit(request, pk):
    treatment = get_object_or_404(Treatment, id=pk)
    form = TreatmentForm(request.POST or None, instance=treatment)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Treatment created successfully.')
        return redirect('treatments:treatment_edit', pk)
    template_name = 'treatments/treatment_edit.html'
    context = {'form': form, 'treatment': treatment}
    return render(request, template_name, context)


@login_required
@admin_required
@permission_required('treatments.disable_treatment', raise_exception=True)
def treatment_disable(request, pk):
    treatment = get_object_or_404(Treatment, id=pk)
    treatment.is_active = False
    treatment.save()
    messages.success(request,
                     'Treatment has been marked as inactive.')
    return redirect('treatments:treatment_list')


def treatment_list_loyalty(request):
    treatment_list = Treatment.objects.filter(is_active=True)
    template_name = 'treatments/treatment_list_loyalty.html'
    context = {'treatment_list': treatment_list}
    return render(request, template_name, context)

treatments/templates/services/area_list.html
{% extends 'base.html' %}

{% block page_title %} Treatment Areas {% endblock %}

{% block content %}

	{% if messages %}
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
    {% endif %}

	<section class="content">
	   <div class="container-fluid">
		  <div class="row">
			 <div class="col-12">
				<div class="card card-outline card-info">
				   <div class="card-header">
					  <h3 class="card-title">Treatment Area List</h3>
					  <div class="card-tools">
						 <a href="{% url 'services:area_create' %}" class="btn btn-sm btn-block bg-gradient-success">
							Add Treatment Area
						 </a>
					  </div>
				   </div>
				   <!-- /.card-header -->
				   <div class="card-body">
					  <table id="treatment_area-table" class="table table-bordered table-hover">
						 <thead>
							<tr>
								<th>ID</th>
								<th>TREATMENT AREA</th>
								<th>ACTIONS</th>
							</tr>
						 </thead>
						 <tbody>
							{% for area in treatment_area_list %}
							<tr>
								<th>{{ area.id}}</th>
								<td>{{ area.area}}</td>
								<td>
									<a href="{% url 'services:area_edit' area.id %}" class="pull-right text-blue">
										<i class="fas fa-pencil-alt"></i></a>
									<a href="{% url 'services:area_delete' area.id %}" class="pull-right text-red">
										<i class="fas fa-trash-alt"></i></a>
								</td>
							</tr>
							{% endfor %}
						 </tbody>
					  </table>
				   </div>
				   <!-- /.card-body -->
				</div>
			 </div>
			 <!-- /.col -->
		  </div>
		  <!-- /.row -->
	   </div>
	   <!-- /.container-fluid -->
	</section>
	<!-- /.content -->

{% endblock %}

treatments/templates/services/pricetype_list.html
{% extends 'base.html' %}

{% block page_title %} Price Types {% endblock %}

{% block content %}

	{% if messages %}
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
    {% endif %}

	<section class="content">
	   <div class="container-fluid">
		  <div class="row">
			 <div class="col-12">
				<div class="card card-outline card-info">
				   <div class="card-header">
					  <h3 class="card-title">Price Type List</h3>
					  <div class="card-tools">
						 <a href="{% url 'services:price_type_create' %}" class="btn btn-sm btn-block bg-gradient-success">
							Add Price Type
						 </a>
					  </div>
				   </div>
				   <!-- /.card-header -->
				   <div class="card-body">
					  <table id="price_type-table" class="table table-bordered table-hover">
						 <thead>
							<tr>
								<th>ID</th>
								<th>PRICE TYPE</th>
								<th>ACTIONS</th>
							</tr>
						 </thead>
						 <tbody>
							{% for ptype in pricing_type_list %}
							<tr>
								<th>{{ ptype.id}}</th>
								<td>{{ ptype.type}}</td>
								<td>
									<a href="{% url 'services:price_type_edit' ptype.id %}" class="pull-right text-blue"><i class="fas fa-pencil-alt"></i></a>
									<a href="{% url 'services:price_type_delete' ptype.id %}" class="pull-right text-red"><i class="fas fa-trash-alt"></i></a>
								</td>
							</tr>
							{% endfor %}
						 </tbody>
					  </table>
				   </div>
				   <!-- /.card-body -->
				</div>
			 </div>
			 <!-- /.col -->
		  </div>
		  <!-- /.row -->
	   </div>
	   <!-- /.container-fluid -->
	</section>
	<!-- /.content -->

{% endblock %}

treatments/templates/services/service_list.html
{% extends 'base.html' %}

{% block page_title %} Services {% endblock %}

{% block content %}

	{% if messages %}
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
    {% endif %}

	<section class="content">
	   <div class="container-fluid">
		  <div class="row">
			 <div class="col-12">
				<div class="card card-outline card-info">
				   <div class="card-header">
					  <h3 class="card-title">Service List</h3>
					  <div class="card-tools">
						 <a href="{% url 'services:service_create' %}" class="btn btn-sm btn-block bg-gradient-success">
							Add Service
						 </a>
					  </div>
				   </div>
				   <!-- /.card-header -->
				   <div class="card-body">
					  <table id="services-table" class="table table-bordered table-hover">
						 <thead>
							<tr>
								<th>ID</th>
								<th>SERVICE NAME</th>
								<th>DESCRIPTION</th>
								<th>ACTIONS</th>
							</tr>
						 </thead>
						 <tbody>
							{% for service in service_list %}
							<tr>
								<td>{{ service.id}}</td>
								<td>{{ service.name }}</td>
								<td>{{ service.description }}</td>
								<td>
									<a href="{% url 'services:service_edit' service.id %}" class="pull-right text-blue"><i class="fas fa-pencil-alt"></i></a>
									<a href="{% url 'services:service_delete' service.id %}" class="pull-right text-red"><i class="fas fa-trash-alt"></i></a>
								</td>
							</tr>
							{% endfor %}
						 </tbody>
					  </table>
				   </div>
				   <!-- /.card-body -->
				</div>
			 </div>
			 <!-- /.col -->
		  </div>
		  <!-- /.row -->
	   </div>
	   <!-- /.container-fluid -->
	</section>
	<!-- /.content -->

{% endblock %}

treatments/templates/services/treatment_list.html
{% extends 'base.html' %}

{% block page_title %} Treatments {% endblock %}

{% block content %}

	{% if messages %}
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
    {% endif %}

	<section class="content">
	   <div class="container-fluid">
		  <div class="row">
			 <div class="col-12">
				<div class="card card-outline card-info">
				   <div class="card-header">
					  <h3 class="card-title">Treatment List</h3>
					  <div class="card-tools">
						 <a href="{% url 'services:treatment_create' %}" class="btn btn-sm btn-block bg-gradient-success">
							Add Treatment
						 </a>
					  </div>
				   </div>
				   <!-- /.card-header -->
				   <div class="card-body">
					  <table id="treatment-table" class="table table-bordered table-hover">
						 <thead>
							<tr>
								<th>ID</th>
								<th>SERVICE</th>
								<th>TREATMENT NAME</th>
								<th>DESCRIPTION</th>
								<th>TREATMENT AREA</th>
								<th>PRICING</th>
								<th>PRICE</th>
								<th>ACTIONS</th>

							</tr>
						 </thead>
						 <tbody>
							{% for treatment in treatment_list %}
							<tr>
								<td>{{ treatment.id}}</td>
								<td>{{ treatment.service }}</td>
								<td>{{ treatment.name }}</td>
								<td>{{ treatment.description }}</td>
								<td>{{ treatment.area }}</td>
								<td>{{ treatment.type }}</td>
								<td>{{ treatment.price }}</td>
								<td>
								  	<a href="{% url 'services:treatment_edit' treatment.id %}" class="pull-right text-blue"><i class="fas fa-pencil-alt"></i></a>
									<a href="{% url 'services:treatment_delete' treatment.id %}" class="pull-right text-red"><i class="fas fa-trash-alt"></i></a>
								</td>
							</tr>
							{% endfor %}
						 </tbody>
					  </table>
				   </div>
				   <!-- /.card-body -->
				</div>
			 </div>
			 <!-- /.col -->
		  </div>
		  <!-- /.row -->
	   </div>
	   <!-- /.container-fluid -->
	</section>
	<!-- /.content -->

{% endblock %}